package org.sonatype.nexus.validation.internal;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.List;

import com.thoughtworks.paranamer.Paranamer;
import org.hibernate.validator.parameternameprovider.ParanamerParameterNameProvider;

/**
 * AOP-aware {@link ParanamerParameterNameProvider}.
 *
 * @since 3.0
 */
public class AopAwareParanamerParameterNameProvider
  extends ParanamerParameterNameProvider
{
  public AopAwareParanamerParameterNameProvider() {
    // empty
  }

  public AopAwareParanamerParameterNameProvider(final Paranamer paranamer) {
    super(paranamer);
  }

  /**
   * Class-name token which indicates class is synthetic generated by Guice AOP.
   */
  private static final String GUICE_ENHANCED = "$$EnhancerByGuice$$";

  private static boolean isEnhancedSubclass(final Class<?> type) {
    return type.getName().contains(GUICE_ENHANCED);
  }

  @Override
  public List<String> getParameterNames(final Constructor<?> constructor) {
    return super.getParameterNames(resolve(constructor));
  }

  /**
   * Resolve constructor for synthetic classes generated by AOP platforms.
   */
  private Constructor<?> resolve(final Constructor<?> constructor) {
    Class<?> type = constructor.getDeclaringClass();
    if (isEnhancedSubclass(type)) {
      try {
        return type.getSuperclass().getDeclaredConstructor(constructor.getParameterTypes());
      }
      catch (NoSuchMethodException e) {
        // ignore
      }
    }
    return constructor;
  }

  @Override
  public List<String> getParameterNames(final Method method) {
    return super.getParameterNames(resolve(method));
  }

  /**
   * Resolve method for synthetic classes generated by AOP platforms.
   */
  private Method resolve(final Method method) {
    Class<?> type = method.getDeclaringClass();
    if (isEnhancedSubclass(type)) {
      try {
        return type.getSuperclass().getDeclaredMethod(method.getName(), method.getParameterTypes());
      }
      catch (NoSuchMethodException e) {
        // ignore
      }
    }
    return method;
  }
}
